import { z } from 'zod';

/**
 * Exact 43-field request contract for the ESLint surface hybrid model.
 */
export const surfaceModelFeaturesSchema = z.object({
  message: z.string(),
  rule_id: z.string().min(1),
  rule_family: z.string().min(1),
  severity_text: z.string(),
  language: z.string(),
  path_extension: z.string(),
  severity: z.number().int(),
  is_error: z.number().int(),
  is_warning: z.number().int(),
  message_length: z.number().int(),
  message_word_count: z.number().int(),
  start_line: z.number().int(),
  start_column: z.number().int(),
  end_line: z.number().int(),
  end_column: z.number().int(),
  finding_span_lines: z.number().int(),
  finding_span_columns: z.number().int(),
  has_fix: z.number().int(),
  fix_text_length: z.number().int(),
  fix_range_length: z.number().int(),
  has_suggestions: z.number().int(),
  suggestion_count: z.number().int(),
  changed_line_start: z.number().int(),
  changed_line_end: z.number().int(),
  changed_line_count: z.number().int(),
  finding_overlaps_change: z.number().int(),
  finding_change_distance: z.number().int(),
  file_size_lines: z.number().int(),
  finding_start_line_ratio: z.number(),
  pr_change_code_lines: z.number().int(),
  base_file_finding_count: z.number().int(),
  base_rule_finding_count: z.number().int(),
  base_file_has_findings: z.number().int(),
  base_rule_exists_in_file: z.number().int(),
  prior_findings_in_file: z.number().int(),
  pr_total_findings_in_file: z.number().int(),
  same_rule_findings_in_file: z.number().int(),
  same_rule_findings_in_repo: z.number().int(),
  path_depth: z.number().int(),
  path_has_test: z.number().int(),
  path_has_src: z.number().int(),
  path_has_config: z.number().int(),
  path_has_generated: z.number().int(),
}).strict();

export type SurfaceModelFeatures = z.infer<typeof surfaceModelFeaturesSchema>;
